removal of bundle from rspec tests

diff --git a/jenkins/client-test b/jenkins/client-test
--- a/jenkins/client-test
+++ b/jenkins/client-test
@@ -64,26 +64,28 @@ else
 fi
 
 # install all of the development gems
-mkdir bundle
+#mkdir bundle
 export PATH=/opt/chef/bin:/opt/chef/embedded/bin:$PATH
-/opt/chef/embedded/bin/bundle config build.eventmachine --with-cflags=-fpermissive
+#/opt/chef/embedded/bin/bundle config build.eventmachine --with-cflags=-fpermissive
 
-# bundle install may fail if the internets are down
-retries=0
-while true; do
-  if /opt/chef/embedded/bin/bundle install --without server docgen --path bundle; then
-    break
-  fi
-  retries=$( expr $retries + 1 )
-  if [ $retries -ge 10 ]; then
-    echo "bundle install failed after 10 retries"
-    exit 1
-  fi
-  echo "retrying bundle install"
-done
+## bundle install may fail if the internets are down
+#retries=0
+#while true; do
+#  if /opt/chef/embedded/bin/bundle install --without server docgen --path bundle; then
+#    break
+#  fi
+#  retries=$( expr $retries + 1 )
+#  if [ $retries -ge 10 ]; then
+#    echo "bundle install failed after 10 retries"
+#    exit 1
+#  fi
+#  echo "retrying bundle install"
+#done
 
 # run the tests
-sudo env PATH=$PATH TERM=xterm /opt/chef/embedded/bin/bundle exec rspec -r rspec_junit_formatter -f RspecJunitFormatter -o $WORKSPACE/test.xml -f documentation spec
+#sudo env PATH=$PATH TERM=xterm /opt/chef/embedded/bin/bundle exec rspec -r rspec_junit_formatter -f RspecJunitFormatter -o $WORKSPACE/test.xml -f documentation spec
+#sudo env PATH=$PATH gem install rspec rspec_junit_formatter
+sudo env PATH=$PATH TERM=xterm rspec -r rspec_junit_formatter -f RspecJunitFormatter -o $WORKSPACE/test.xml -f documentation spec
 
 # clean up the workspace to save disk space
 cd $WORKSPACE
